import type { Metadata } from 'next';
import Script from 'next/script';
import './globals.css';
import PageAtom from '@/atoms/layouts/PageAtom';
import Header from '@/components/layouts/Header';
import Footer from '@/components/layouts/Footer';
import RouteHandler from '@/components/utils/RouteHandlerComp';
import ScrollToTopOnMountComp from '@/components/utils/ScrollToTopOnMountComp';
import { Analytics } from '@vercel/analytics/next';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <RouteHandler />
      <ScrollToTopOnMountComp />
      <html lang="en">
        <head>
          <Script async src="https://www.googletagmanager.com/gtag/js?id=G-BNJFVEGEQV" />
          <Script id="google-analytics">
            {`
              window.dataLayer = window.dataLayer || [];
              function gtag(){dataLayer.push(arguments);}
              gtag('js', new Date());

              gtag('config', 'G-BNJFVEGEQV');
            `}
          </Script>
          {/* <script async src="https://www.googletagmanager.com/gtag/js?id=G-BNJFVEGEQV"></script>
          <script
            dangerouslySetInnerHTML={{
              __html: `
              window.dataLayer = window.dataLayer || [];
              function gtag(){dataLayer.push(arguments);}
              gtag('js', new Date());
              gtag('config', 'G-BNJFVEGEQV');
            `,
            }}
          /> */}
        </head>
        <body className={'flex justify-center items-center'}>
          <Analytics />
          <PageAtom>
            <Header />
            {children}
            <Footer />
          </PageAtom>
        </body>
      </html>
    </>
  );
}
