import type { Metadata } from 'next';
import './globals.css';
import PageAtom from '@/atoms/layouts/PageAtom';
import Header from '@/components/layouts/Header';
import Footer from '@/components/layouts/Footer';
import RouteHandler from '@/components/utils/RouteHandlerComp';
import ScrollToTopOnMountComp from '@/components/utils/ScrollToTopOnMountComp';
import { Analytics } from '@vercel/analytics/next';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <Analytics />
      <RouteHandler />
      <ScrollToTopOnMountComp />
      <html lang="en">
        <body className={'flex justify-center items-center'}>
          <PageAtom>
            <Header />
            {children}
            <Footer />
          </PageAtom>
        </body>
      </html>
    </>
  );
}
